- LICENSE
- package.json
Somebody will ask us to do it eventually, so this is here to head it all off at the pass :)
> add license and package repository information

- package.json
- src/components/01-atoms/RoomLabel/index.js
- src/components/01-atoms/RoomLabel/styles.scss
- src/components/App/index.js
- src/components/App/index.test.js
- src/reducers/index.js
- src/routes/index.js
Tests and linting must pass before code can be committed. You can still force a commit by telling git to skip the pre-commit hooks by committing using --no-verify.
> Add validation to pre-commit hook

- src/api/index.js
- src/components/03-organisms/Agenda/index.js
- src/reducers/index.js
- src/sagas.js
- src/shared-styles/bookit.scss
Put data onto Redux state tree
Transform data to meet api of Agenda view
Put onto the state tree data necessary for displaying the Event "tooltip"
> Fetch real data from local dev Bookit server

- .eslintrc.json
- .flowconfig
- package.json
We decided to back away from flow at this time, so there is no need for the dependencies and configuration for it.
> remove flow-related dependencies and configuration

- .travis.yml
My editor seems to have gone crazy reformatting this file. The only actual change is to the "secure" line under "slack." This *should* fix the Slack integration for Travis. If it does, I will do the same for bookit-server.
> Fix Travis integration

- .gitignore
- README.md
- func-test/index.js
- package.json
- seleniumSetup.sh
- src/containers/Login/index.js
- wdio.conf.js
- See the README for instructions on how to run this. Requires a Selenium server to be running locally.
- Using Selenium via webdriver.io
- Only does a very basic test to check that the app is alive
> Add functional test framework and very basic ru alive tests

- src/containers/Dashboard/index.js
- fixed this to refer to the correct property
> The title/subject for the meeting wasn't showing up in the UI

- src/containers/Login/index.js
> Changed button text on login screen from "Bookit" to "Login".

- src/components/02-molecules/RoomTimeline/styles.scss
- src/shared-styles/variables.scss
Makes the divider lines less visually prominent. 
This came out of design/dev pairing with myself, Lawrence, and @ntibaldi92
> Modify appearance of Timeline divider 

- src/components/01-atoms/Tooltip/index.js
- src/components/01-atoms/Tooltip/styles.scss
This came out of design/dev live coding with Lawrence and @ntibaldi92
> Modify text style of Meeting Tooltip

- src/actions/auth.js
Merge in conjunction with bookit-server branch with same name.
> fix SET_USER related weirdness from server auth response

- src/components/02-molecules/Meeting/index.js
- src/containers/Dashboard/index.js
This used to be there, but got regressed out with a recent change. Just adding it back in.
> Outline the selected meeting with a very yellow line

- src/components/01-atoms/Calendar/DateDisplay/index.js
- src/components/01-atoms/Calendar/index.js
- src/utils/calendar/index.js
Arrows on either side of the calendar shift the month back and forth.
> Month rockers

- .travis.yml
- src/components/01-atoms/TimelineLabelList/index.test.js
- src/components/01-atoms/Tooltip/TooltipAnchor.test.js
- src/components/01-atoms/Tooltip/TooltipContent.js
- src/components/01-atoms/Tooltip/TooltipContent.test.js
- src/components/01-atoms/Tooltip/index.test.js
- src/components/02-molecules/ConfirmationDialog/index.test.js
- src/components/02-molecules/ErrorMessages/index.test.js
- src/components/02-molecules/Header/index.test.js
Day One of adding unit tests + supporting fixtures
> Add unit tests

- src/components/01-atoms/Calendar/index.js
- src/components/01-atoms/Calendar/styles.scss
- src/components/02-molecules/MeetingForm/index.js
- src/components/02-molecules/ReservationList/styles.scss
- src/components/02-molecules/UserForm/index.js
- src/components/02-molecules/UserForm/styles.scss
- src/components/03-organisms/SearchableUserTable/SearchBar/styles.scss
- src/components/03-organisms/SearchableUserTable/TeamSelector/styles.scss
- src/components/03-organisms/SearchableUserTable/UserTableRow/index.js
- src/components/03-organisms/SearchableUserTable/UserTableRow/styles.scss
- src/components/03-organisms/SearchableUserTable/styles.scss
- src/containers/Admin/styles.scss
- src/containers/InfoPanel/index.js
- src/containers/InfoPanel/styles.scss
- src/containers/MeetingForm/index.js
- src/containers/UserForm/index.js
This branch is somewhat-inappropriately named 'design-polish' as that's what it started out as...
Within these changes:
- Rows in the user table are highlighted on hover 
- "Remove" does not display unless the user row is highlighted
- "+" and "x" buttons are now one and the same, and live in only one place
- ...with CSS classes that switch based on state... whaaaa??
- Also tried to clean up the logic in InfoPanel so that it's easier to follow
- Note: The "+" button on the AgendaView currently does nothing - this is supposed to be for "Quick Book" which has not yet been implemented
> clean up infopanel and create add/close button

- design-deliverables/README.md
contains prototypes, assets, user stories, etc.
> design-folder-creation

- design-deliverables/README.md
corrected a few markdown formatting mistakes
> silly formatting errors

- src/components/03-organisms/SearchableUserTable/index.js
- src/components/03-organisms/SearchableUserTable/index.test.js
This PR makes a slight change to the search filter, allowing for a match starting on the first letter of the first or last name.
> User search - filter on first or last name

- src/components/01-atoms/Calendar/DateDisplay/index.js
- src/components/01-atoms/Calendar/DateDisplay/index.test.js
- src/components/01-atoms/Calendar/Day/index.js
- src/components/01-atoms/Calendar/Day/index.test.js
- src/components/01-atoms/Calendar/DayNames/index.test.js
- src/components/01-atoms/Calendar/Week/index.test.js
- src/components/01-atoms/Calendar/index.js
- src/components/01-atoms/Calendar/index.test.js
- src/containers/Admin/index.js
- src/containers/Admin/index.test.js
This PR adds tests to the calendar component, as well as all of its' subcomponents.
> Enzyme tests

- src/api/azure.js
- this really needs to be fixed
> Updating azure identity

- src/components/02-molecules/MeetingForm/index.js
- src/containers/MeetingForm/index.js
Fixes https://kanbanflow.com/t/5a7e8bd042bc161bd85acde29d3ad62b/8-open-assessment-bookit-button-is-enab
> Disable submit button if meeting date is in the past

- src/components/02-molecules/MeetingForm/index.js
Form submission button was enabled when for was invalid, in some cases.
This commit fixes the bug.
> :bug: Fix meeting form bug

- src/components/02-molecules/MeetingForm/index.js
A minor change, intended to improve readability of the logic related to meeting form validation.
> Improve name of util

- src/api/auth.js
- src/api/index.js
- src/api/meetings.js
- src/api/users.js
- src/api/utils.js
This commit cleans up the `api` code. This is necessary for moving forward with [the list users story](https://kanbanflow.com/t/096fa42b062dbc8c82febb2a0c3f3707/3-as-an-admin-i-want-to-list-users-m).
> Clean up api

- src/api/meetings.js
> Edit meetings bugs

- src/reducers/user.js
- src/utils/check-auth.js
- src/utils/check-auth.test.js
Client side updates required for https://kanbanflow.com/t/9218ae9d2bd4d7fe3dfb133bf2d9f40b/44-as-a-new-user-i-want-to-be-able-to-lo
> Slight changes to accommodate changes to server side auth process

- src/api/azure.js
- src/containers/OpenId/index.js
- src/containers/OpenId/index.test.js
Get multi tenant stuff working..
There will be clean up of the tenant ids so that we get this information from the server.
> 59 multitenant

- sprint-docs/11-demo-plan-general-demo.md
This is a general demo of Bookit, presented to the Designit team in Dumbo.
> First draft of demo plan
