buildit/bookit-web

- .eslintrc.json
- .flowconfig
- package.json
- src/components/01-atoms/RoomLabel/index.js
- Demo a very simple example of Flow usage in RoomLabel/index.js
- Modify ESLint config to play nice with Flow. See: https://github.com/gajus/eslint-plugin-flowtype and http://stackoverflow.com/questions/36258234/eslint-with-arbnb-config-and-facebook-flow-together
- Trick Flow into playing nice with scss module imports. See: https://github.com/facebook/flow/issues/338
> Add support for Flow

- README.md
- package.json
In following (what seems to be) a node convention, I'm aiming to make it a little bit easier to remember how to start this thing up in dev mode. `npm run dev` is very specific to our app. By aliasing `npm start` we can give an easy, recognizable entry point.
> Specify a start script

- src/components/01-atoms/Tooltip/index.js
Fixed the meeting title overflow that was occurring in the tooltip. Truncated the title for anything over 25 characters.
> Tooltip overflow

- src/components/01-atoms/Calendar/DateDisplay/styles.scss
- src/components/01-atoms/Calendar/styles.scss
- src/components/03-organisms/Agenda/styles.scss
- src/containers/Dashboard/index.js
- src/containers/Dashboard/styles.scss
This PR moves the "Hello {user} | Logout" block within the app so that the black calendar area takes up the entire left side, as seen in Zeplin.
> style app to match zeplin

- package.json
- src/actions/auth.js
- src/actions/meetingCreate.js
- src/api/index.js
- src/components/02-molecules/MeetingForm/index.js
- src/components/02-molecules/ReservationList/index.js
- src/containers/Dashboard/index.js
- src/containers/MeetingForm/index.js
- src/functional-tests/tests/login.js
- src/sagas/meetings.js
- src/sagas/meetings.test.js
* Now uses the protected meeting creation endpoint from bookit-server
* Reservations List now shows meetings for the currently logged in user
* Sort of tried to avoid relying on `isOwnedByUser`, since it is a derived property and not pure state
This PR should be accepted once the server-auth branch of bookit-server is merged into its master.
> Use actual authentication from bookit-server

- src/actions/meetingsFetch.js
- src/components/01-atoms/RoomTimelineNames/index.js
- src/components/01-atoms/Tooltip/TooltipContent.js
- src/components/01-atoms/Tooltip/index.js
- src/components/02-molecules/Meeting/index.js
- src/components/02-molecules/ReservationList/index.js
- src/components/02-molecules/RoomTimeline/index.js
- src/components/03-organisms/Agenda/index.js
- src/containers/Dashboard/index.js
- src/reducers/app.js
- src/sagas/meetings.js
The meetings data as received from the server is deeply nested, which has caused our components to perform all sorts of weird contortions. The reducer logic was overly complex, not to mention the weird mappings and reductions we had going on in several components.
This commit flattens the meeting data. Hopefully this will make the application state much easier to work with. The logic for retrieving or updating a given item is now fairly simple and consistent. For instance, given a meeting's ID, we can directly look it up and figure out which room it's in a couple simple steps, without having to dig through other objects to do so. No more `roomMeeting.room.meeting.room`!
Here's how the Actions, Containers, and Dumb Components work together under this scheme:
The application state is …
> Normalize state

- src/components/01-atoms/Calendar/index.js
- src/components/02-molecules/Header/index.js
- src/components/02-molecules/Header/styles.scss
- src/containers/Dashboard/index.js
- src/containers/Dashboard/styles.scss
- src/containers/InfoPanel/index.js
- src/containers/InfoPanel/styles.scss
The `Dashboard` component was handling a lot of different things at once -- probably too much. This commit creates `Header` and `InfoPanel` components, which are children of `Dashboard`.
This `InfoPanel` is not only badly named, it also serves as a container for the `Calendar`, the `ReservationList`, and the various forms that appear on the left.
> Restructure the Dashboard component

- src/components/01-atoms/Button/styles.scss
- src/components/01-atoms/Calendar/Day/index.js
- src/components/01-atoms/Calendar/Day/styles.scss
- src/components/01-atoms/Tooltip/TooltipContent.js
- src/components/02-molecules/Meeting/styles.scss
- src/components/02-molecules/ReservationList/styles.scss
- src/containers/Dashboard/styles.scss
- src/utils/calendar/index.js
Bookit needed some style cleanup, mostly in the left "info pane," but also in some other areas where changes got lost in the shuffle.
This PR updates some of the styles in the "edit" form (namely the button font and padding), "my reservations" (font sizes, cursor), the header (font weight), and re-implements some of the styles in the tooltip content which were lost after a dev-design pairing session with Lawrence.
This also implements the underline for the current date on the calendar.
> Style cleanup for left pane, tooltip content, and header

- webpack/parts/style.js
The meetings appear to be overly large. This commit fixes the issue.
Webpack should use the same CSS class naming scheme (i.e. `localIdentName`) in both in-memory styles, which are used by Webpack dev server, and the built CSS files, which are used in the built app.
> Fix meetings style :bug:

- .travis.yml
- package.json
- src/functional-tests/tests/login.js
Functional tests should run after the app has been built, they should run against the latest version of the bookit-server, and the test conditions should match the eventual deployed conditions. If the functional tests fail, the Travis build should fail.
This commit accomplishes this: It adds a step to Travis that builds and containerizes the app within the Travis environment. It then pulls the latest container of the bookit server, runs both containers, and then runs the functional tests.
Right now, there is only one test, but this work should allow us to add any other functional tests we like.
Devs can run the functional tests locally just as before: `npm run test:functional`. Hipsters may use `yarn test:functional`.
> Add functional test step to Travis

- .jestrc.json
- package.json
- src/components/01-atoms/Link/index.js
- src/components/01-atoms/Link/index.test.js
- src/components/02-molecules/Header/index.js
- src/components/02-molecules/Header/index.test.js
- src/components/02-molecules/Header/styles.scss
- src/components/02-molecules/Meeting/index.js
- src/components/02-molecules/Meeting/index.test.js
- src/components/02-molecules/MeetingCancel/index.js
- src/components/02-molecules/MeetingCancel/index.test.js
- src/components/02-molecules/Messages/index.test.js
- src/components/02-molecules/RecentlyAddedUsersTable/index.test.js
- src/components/02-molecules/ReservationList/ReservationItem.js
- src/components/02-molecules/ReservationList/ReservationItem.test.js
- src/components/02-molecules/ReservationList/index.js
- src/components/02-molecules/ReservationList/index.test.js
- src/components/02-molecules/RoomTimeline/index.test.js
- src/components/03-organisms/Agenda/index.js
- src/components/03-organisms/Agenda/index.test.js
Day Three of adding unit tests.
Changes made to source modules are a result of either:
1. Needing to expose a value or function to ensure tests were using correct values without having to just hardcode them into the tests with little to no explanation
2. Requiring fixes due to flaws exposed during testing
Note that when testing components that are `connect`ed to redux, the pattern for unit testing _just_ the component requires us to export the named component, and exporting the connected component as the default (which we were doing anyway).
> Add more unit tests

- .travis.yml
- scripts/push-docker-image.sh
- scripts/run-functional-tests.sh
Reason for this is each `script` invocation in travis is ideally meant to be a single pass/fail item.
Our current travis script includes multiple steps (all of which can yes, pass or fail) that are in fact boilerplate to allow for specific test suites and/or build steps to run.
By isolating these boilerplate script items into distinct bash scripts, we reduce the clutter of the `scripts` block and make it clear what we are actually intending to achieve with each script.
For clarification, the `set -ev` call inside each bash script added in this PR ensures that each script echoes each call within said script (the `v` flag) and will fail-fast on _any_ call that failed (the `e` flag) and prevent additionally lines from running (since there's no point running additional steps if a prior one …
> Tidy travis scripts

- CODE_OF_CONDUCT.md
This is the final revision of my - hopefully opinion-free - guidelines on writing unit tests.
This PR is essentially an RFC to contribute ideas on how to make testing better and/or more understandable in the case of new devs coming on board.
Also, the naming of the file CODE_OF_CONDUCT.md is due to this kind of file apparently being a "thing" in some development worlds, and as such can be expanded to include more guidelines on any aspect of how to contribute to this codebase (I guess maybe it should be called CONTRIBUTING.md? I don't know).
> add unit testing guidelines under the umbrella CODE_OF_CONDUCT file

- .gitignore
- .travis.yml
- src/api/index.js
- src/sagas/meetings.js
- src/sagas/meetings.test.js
- src/selectors.js
Relates to [bookit-server PR #26: Meeting Visibility](https://github.com/buildit/bookit-server/pull/26).
All bookit-server endpoints that support the use of an auth token are now given said auth token via the `X-Access-Token` header on request.
The auth token is pulled from the user state object using the redux-saga `select` effect, passing a valid selector from the newly added `selectors.js` module.
> add auth token to API calls

- .browserlistrc
- package.json
- webpack/parts/javascript.js
- yarn.lock
This change will allow us to make "best effort" attempts to support all browser versions the client would like us to support, but beyond automatically polyfilling client-side javascript and post-fixing CSS at build-time, this offers no guarantees or tests for said supported browsers.
Improvements to the code were made to avoid repeating the supported browsers list in both `.browserslistrc` _and_ `webpack/parts/javascript.js` by making use of the actual `browserslist` node library (which was already installed as a dependency of some other library, but is now a clearly declared dev dependency of bookit-web).
> unify sources of supported browsers

- src/components/01-atoms/Tooltip/TooltipContent.js
- src/components/01-atoms/Tooltip/TooltipContent.test.js
- src/components/01-atoms/Tooltip/index.js
- src/components/01-atoms/Tooltip/index.test.js
- src/components/02-molecules/Meeting/index.js
- src/components/02-molecules/Meeting/index.test.js
This PR aims to resolve the bug in the meeting editor in which the form does not populate correctly when clicking on "edit" a second time (without closing the edit form). For now, we are hiding the "edit" button when "isEditingMeeting" is true.
> Doesn't display edit button to user when already editing a meeting

- .jestrc.json
- .travis.yml
CAVEAT: There is no ticket for this, I am a jerk.
Hey! You want an instant percentage boost on coveralls? I know you do!
We are a little dumb and did not exclude src/functional-tests from jest's coverage collection.
I feel it's pretty fair that we don't want to include coverage of tests. Probably.
Also, as a bonus: travis now emits COLORS when running tests! It also suppresses console.log output from modules under test! IT'S AMAZING!
> Prevent src/functional-tests from being counted towards coverage

- src/components/02-molecules/UserForm/index.js
- src/components/02-molecules/UserForm/styles.scss
- src/reducers/app.js
- src/reducers/users.js
- src/sagas/users.js
Resolves: https://kanbanflow.com/t/5a7e8bd042bc161bd85acde29d3e3f32/10-as-an-admin-i-want-to-add-invite-use
- Some small changes to what we send over the wire.
- Hardcode team (Wipro) and location (New York) for all added users. This happens in one spot on the client: `sagas/users.js`
- Email addresses must be valid (sort of) before the button is enabled.
> Modify "Add user" functionality to match server

- src/reducers/app.js
When the user invitation succeeds, the admin is shown a message. This
commit fixes a bug that caused the message to read "undefined has been
added".
> Fix bug in user invitation process

- src/components/02-molecules/ConditionalRouteLink/index.js
- src/components/02-molecules/ConditionalRouteLink/index.test.js
- src/components/02-molecules/Header/index.js
- src/components/02-molecules/Header/index.test.js
- src/utils/check-auth.js
Ticket: https://kanbanflow.com/t/9218ae9d2bd4d7fe3dfb133bf27e5871/43-as-an-admin-i-want-to-access-the-us
Ensures that the (admin) user sees the correct links in the header to navigate between the users and timeline pages.
This PR introduces a new `ConditionalRouteLink` component, which is essentially a `Route` component (from react-router) that wraps a `Link` component.
The idea is that since you can use `Route` components anywhere inside an app, you can use its own functionality to decide if the `children` props will get rendered based on the `match` property that the route resolves from the parent `Router`.
Currently a `ConditionalRouteLink` will render only when the `path` prop _exactly_ matches the current `history.location.pathname` value.
The `match` prop will either be `null` if …
> 43 admin navigation

- src/components/01-atoms/Tooltip/TooltipContent.js
- src/components/01-atoms/Tooltip/TooltipContent.test.js
- src/components/02-molecules/DateTimePicker/index.js
- src/components/02-molecules/MeetingForm/index.js
- src/components/02-molecules/ReservationList/ReservationItem.js
- src/components/02-molecules/ReservationList/ReservationItem.test.js
- src/containers/MeetingForm/index.js
This branch handles allowing users to edit meetings in various states.
The `edit` button is obscured for meetings that have already ended (`end` time is in the past), both on the tooltip and in the reservation list.
Meetings that are in progress can be edited, but only the end time can be changed (a user can't move the start time farther into the past). This is handled by disabling the date/time picker for the meeting start.
The user cannot submit an edit if the new start or end time is in the past.
> 50 in progress rules

- webpack.config.babel.js
remove console.log from webpack config as it can mess with various stats-related tools output.
To be honest, it should have never been in there - it was a vestigial leftover from where I was debugging the crap out of running webpack with webpack-merge. It just stuck around because it never really caused a problem (until I tried to run an analysis on overall size of the production build, where the log statement was getting injected into the output file of the stats used for analysis).
> [OOB] Remove unnecessary console.log from webpack config

- .travis.yml
- package.json
- src/components/02-molecules/DateTimePicker/index.js
- src/components/02-molecules/DateTimePicker/styles.scss
- src/components/02-molecules/MeetingForm/index.js
- src/containers/MeetingForm/index.js
- src/index.ejs
- yarn.lock
This PR replaces the `material-ui` date and time picker with `React-Kronos.`
As of now, all of the meeting form's validations/behavior remain the same, but Kronos allows for us to:
- customize the date/time formats
- prevent the user from clicking on dates in the past
- prevent display of times in the past
- customize the meeting time intervals
This is much more user-friendly and less confusing.
The date and time `input` fields in Kronos are easily customized via the component's props. Unfortunately, some hacky CSS magic in the `index.ejs` was required to make the datepicker's calendar and timepicker's dropdown look consistent with the designs for Bookit.
> 70 date time picker
